name: CI Automático

on:
  push:
    branches:
      - main  # ou a branch que você usa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Node (exemplo)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Finalizado
        run: echo "Pipeline concluído!"
